config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    has_many :allergies
    has_many :users, through: :allergies

    def self.sort_by_alergics
        self.all.sort_by { |r| -r.allergies.count }
      end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients ###
  has_many :ingredients, through: :recipe_ingredients

    def self.sort_by_ingredients
      self.all.sort_by { |r| -r.ingredients.count }
    end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes, dependent: :destroy
    has_many :allergies, dependent: :destroy
    # has_many :ingredients, through: :allergies
    # has_many :ingredients, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    def index
        @ingredients = Ingredient.sort_by_alergics
    end
    def show
        @ingredient = Ingredient.find(params[:id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.sort_by_ingredients
    end
    def new
        @recipe = Recipe.new
    end
    def create
        recipe = Recipe.create(paramas_recipe)
        if recipe.valid?
            redirect_to recipes_path
        else
            redirect_to new_recipe_path
        end
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    private
    def paramas_recipe
     params.require(:recipe).permit(:name, :user_id, ingredient_ids: [])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end

    def destroy
        user = User.find(params[:id])
        user.destroy

        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>Ingredients </h1>

<ul>
<% @ingredients.each do |i| %>
<li><%= link_to i.name, i %> - <%= i.allergies.count %></li>
<% end %>
</ul>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<% @ingredient.recipes.each do |recipes| %>
 <ul><li><%= link_to recipes.name, recipes%></li></ul>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <%= link_to "Recipes", recipes_path %>
    <%= link_to "Users", users_path %>
    <%= link_to "Ingredients", ingredients_path %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1> Recipes </h1>
<ul>
<% @recipes.each do |r| %>
<li><%= r.name %> - <%= r.recipe_ingredients.count %></li>
<% end %>
</ul>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :user %>
    <%= f.collection_select :user_id, User.all, :id, :name%>

    <%= f.label :ingredient_ids %>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>

    <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<%= @recipe.name %>
<% @recipe.ingredients.each do |ing| %>
<ul><li><%= ing.name %></li></ul>
<% end %>
<%= link_to @recipe.user.name, @recipe.user %>

app/views/users/index.html.erb
<h1> Users </h1>
<% @users.each do |user| %>
    <ul><li><%= link_to user.name, user %></ul></li>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% @user.recipes.each do |recipes| %>
 <ul><li><%= link_to recipes.name, recipes%></li></ul>
 <% end %>

 <%= link_to "Delete User", user_path(@user), method: "delete", data: {confirm: 'are you sure, you will lose all your recipes'} %>